config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  root "items#index"

  resources :items
  get 'logout', to: 'items#logout'
  get 'identification', to: 'items#identification'
  get 'edit_profile', to: 'items#edit_profile'
  get 'item_edit_delete', to: 'items#item_edit_delete'

  get 'identification', to: 'items#identification'
  get 'identification', to: 'items#identification'
  get 'mypage', to: 'items#mypage'
  

  get 'purchase/:id', to: 'purchase#index'

  resources :purchase, only: [:index,:update] do
    member do
      post 'pay'
      get 'done'
    end
  end
  
  resources :users, only: [:new, :edit, :create, :show]
  

  resources :signup, except:[:index,:show] do
    collection do
      get 'step1'
      post 'save_step1'
      post 'step2'
      post 'save_step2'
      post 'step3'
      post 'save_step3'
      get 'complete' # 登録完了後のページ
    end
  end


  get 'mypage/credit/:id', to: 'cards#credit'
  get 'registration', to: 'cards#registration'

  resources :cards, only: [:new, :create, :show, :destroy]

end

app/controllers/purchase_controller.rb
class PurchaseController < ApplicationController
  require 'payjp'
  
  before_action :set_card, :set_item
        
  def index
    if @card.blank?
      #登録された情報がない場合にカード登録画面に移動
      redirect_to controller: "cards", action: "new"
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      #保管した顧客IDでpayjpから情報取得
      customer = Payjp::Customer.retrieve(@card.customer_id)
      #保管したカードIDでpayjpから情報取得、カード情報表示のためインスタンス変数に代入
      @card_information = customer.cards.retrieve(@card.card_id)
    end
  end

  def pay
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    Payjp::Charge.create(
    :amount => @item.price,          #支払金額を引っ張ってくる
    :customer => @card.customer_id,  #顧客ID
    :currency => 'jpy',              #日本円
  )
  @item.update(buyer_id: current_user.id) 
  redirect_to action: 'done' #完了画面に移動
  end

  def done
  end

  def update
    item = Item.find(params[:id])
    item.update(item_params)
    redirect_to action: 'show' 
  end

private

  def item_params
    params.require(:item).permit(:buyer_id)
  end


  def set_card
    @card = Card.where(user_id: current_user).first
  end
  
  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/purchase_helper.rb
module PurchaseHelper
end

app/views/purchase/done.html.haml
= render 'users/user-single-header'
.buy__alert
  .buy__alert__top
    %i.far.fa-clock.alert__icon
    .buy__alert__top__text
      発送をお待ちください
  .buy__alert__bottom
    出品者からの発送通知をお待ちください
.buy__centerbox
  .buy__centerbox__head
    購入が完了しました
  .buy__centerbox__item
    .buy__centerbox__item__bx
      .buy__centerbox__item__bx__image
        -# = image_tag "#{@item.image}"
      .buy__centerbox__item__bx__right
        .buy__centerbox__item__bx__right__name
          -# = @item.name
        .buy__centerbox__item__bx__right__detail
          -# - i_price = @item.price.to_s
          -# = "¥" + i_price + " (税込) 送料込み"
  .buy__centerbox__buyinfo
    .buy__centerbox__buyinfo__price
      .buy__centerbox__buyinfo__price__upper
        .buy__centerbox__buyinfo__price__upper__detail
          支払い金額 
        .buy__centerbox__buyinfo__vprice__upper__price
          -# = "¥" + i_price
    .buy__centerbox__buyinfo__buybutton
      = link_to root_path do
        %button.btn{type:"submit",class:"buy__centerbox__buyinfo__buybutton__red"}
          戻る
= render 'users/footer'

app/views/purchase/index.html.haml
= render 'users/user-single-header'
%main.item_confirm
  %section.item_confirm__content
    %h2.item_confirm__content__head
      購入内容の確認
    %section.item_confirm__content__buy-item
      .item_confirm__content__buy-item__inner
        .item_confirm__content__buy-item__inner__box
          .item_confirm__content__buy-item__inner__box__img
            = image_tag "#{@item.image}",class:"item-image"
          .item_confirm__content__buy-item__inner__box__detail
            %p.item_confirm__content__buy-item__inner__box__detail__name
              =@item.name
            %p.item_confirm__content__buy-item__inner__box__detail__price
              %span 
                ¥ 
                =@item.price
              %span.item-confiem__fee （税込）送料込み
    .item_confirm__content__buy-container
      .item_confirm__content__buy-container-inner
        .item_confirm__content__buy-container-inner__price
          %ul.item_confirm__content__buy-container-inner__price__detail
            %li.item__price
              支払い金額
            %li.inner__price
              ¥
              =@item.price
          .item-confirm__points
            %input.inner-box{type: "checkbox"}
            %p.inner-point ポイントを使用
        .item_confirm__content__buy-container-inner__credit
          %ul.item_confirm__content__buy-container-inner__credit__lists
            %li.inner__method
              支払い方法
            %li.inner__option
              変更する

          .item_confirm__content__buy-container-inner__credit__cards
            %p.tem_confirm__content__buy-container-inner__credit__cards__info
              クレジットカード
              .card-logo
              = "**** **** **** " + @card_information.last4
              %br/
              - exp_month = @card_information.exp_month.to_s
              - exp_year = @card_information.exp_year.to_s.slice(2,3)
              = "有効期限" + exp_month + " / " + exp_year
            = image_tag "visa.gif",class:"item_confirm__credit-card"
        .item_confirm__content__buy-container-inner__address
          %ul.item_confirm__content__buy-container-inner__address__info
            %li.address-info 
              配送先
              %br/
              〒000-0001
              %br/
              北海道 夕張市
              〇〇町0-0-3
              %br/
              kojikoji
              -# = @item.user.name
            %li.section-info 変更する
        .item_confirm__content__buy-container-inner__form
          %p.item_confirm__content__buy-container-inner__form__content
            この商品は、ゆうゆうメルカリ便を利用しているため、アプリからのみ購入できます。
            = form_tag(action: :pay, method: :post) do
              %button.btn{type:"submit",class:"buy__centerbox__buyinfo__buybutton__red"} 購入する
          -# = link_to "購入する", done_purchase_path, method: :post
          %p.item_confirm__content__buy-container-inner__form__app
            アプリをお持ち出ない方は以下よりインストールしてご利用いただけます。
          %br/
= render 'users/footer'