config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  root "items#index"

  resources :items
  get 'logout', to: 'items#logout'
  get 'identification', to: 'items#identification'
  get 'edit_profile', to: 'items#edit_profile'
  get 'item_edit_delete', to: 'items#item_edit_delete'

  get 'identification', to: 'items#identification'
  get 'identification', to: 'items#identification'
  get 'mypage', to: 'items#mypage'
  

  get 'purchase/:id', to: 'purchase#index'

  resources :purchase, only: [:index,:update] do
    member do
      post 'pay'
      get 'done'
    end
  end
  
  resources :users, only: [:new, :edit, :create, :show]
  

  resources :signup, except:[:index,:show] do
    collection do
      get 'step1'
      post 'save_step1'
      post 'step2'
      post 'save_step2'
      post 'step3'
      post 'save_step3'
      get 'complete' # 登録完了後のページ
    end
  end


  get 'mypage/credit/:id', to: 'cards#credit'
  get 'registration', to: 'cards#registration'

  resources :cards, only: [:new, :create, :show, :destroy]

end

app/models/item.rb
class Item < ApplicationRecord
  mount_uploader :image, ImageUploader
  
  # has_many :images, dependent: :destroy
  # belongs_to :category
  belongs_to :user
  # belongs_to :category_id

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  
  layout "items"

  before_action :set_item, only: [:show, :edit, :destroy]

  def index
    @items = Item.all
  end

  def show
    @items = Item.all
    @images = @item.image
  end
  
  def new
    @item=Item.new
    render :layout  => "application"
  end


  def credit
    # @item = Item.find(params[:id])
    Payjp.api_key = ENV['PAYJP_PRIVATE_KEY']
    Payjp::Charge.create(
      amount: @item.price
      # card: params['payjp-token']
      # currency: 'jpy'
    )
  end
  
  def create
    @item=Item.new(item_params)
    if @item.save
        redirect_to root_path
      else
        render "items/new"
      end 
    end
    
    
  def mypage
  end


  def edit
    render :layout  => "application"
  end

  def update
    item = Item.find(params[:id])
    if item.update(item_params)
      redirect_to item_path(item.id)
    else
      redirect_to edit_item_path(item.id)
    end
  end

  def destroy
    if @item.destroy # .include?(@item.user_id == current_user.id)
      redirect_to root_path
      flash[:success] = '商品情報を削除しました'
    else
      redirect_to item_path(item.id)
      flash[:danger] = '商品情報の削除に失敗しました'
    end
  end


  private
  
  def item_params
    params.require(:item).permit(:name, :detail, :category_id, :state, :delivery_fee, :prefecture_id, :delivery_date, :price, :fee, :gross_profit, :size, :image).merge(user_id: current_user.id)
  end
  
  def set_item
    @item = Item.find(params[:id])
  end

end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_footer.html.haml
%footer
  .smph__area
    = image_tag 'room_image.jpg', class:'smph__img'
    .smph__area__contents
      %p.smph__text1 スマホでかんたんフリマアプリ
      %p.smph__text2 今すぐ無料ダウンロード!
      = image_tag 'logo_white.svg', class:'footer__fma__img'
      = image_tag 'apple_icon.svg', class:'footer__apple__img'
      = image_tag 'google_icon.svg', class:'footer__google__img'
      = image_tag 'free_img.png', class:'footer__free__img'
    
  .footer__index
    .footer__index__top
      .footer__index__contaner
        %ul.footer__index__box
          %li.footer__title メルカリについて
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 会社概要（運営会社）
          / target="_blank"はリンクボタンを押すと別タブが開く
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 採用情報
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} プレスリリース
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 公式ブログ
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} メルカリロゴ利用ガイドライン

          %li.footer__btn
            %a.footer__btn__twitter{:href => "#"}
              %i.fab.fa-twitter
            %a.footer__btn__facebook{:href => "#"}
              %i.fab.fa-facebook-square

        %ul.footer__index__box
          %li.footer__title ヘルプ＆ガイド
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} メルカリガイド
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} らくらくメルカリ便
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} ゆうゆうメルカリ便
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 大型メルカリ便
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 車体取引ガイド
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} メルカリあんしん・あんぜん宣言！
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 偽ブランド品撲滅への取り組み
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} メルカリボックス

        %ul.footer__index__box
          %li.footer__title プライバシーと利用規約
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} プライバシーポリシー
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} メルカリ利用規約
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} あんしんスマホサポート制度に関する利用特約
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} コンプライアンスポリシー
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 個人データの安全管理に係る基本方針
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 特定商取引に関する表記
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 資金決済法に基づく表示
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 法令順守と犯罪抑止のために

        %ul.footer__index__box
          %li.footer__title 国
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} 日本
          %li.footer__comments
            %a.footer__comment{:href => "#", :target => "_blank"} United States

    .footer__index__bottom
      = image_tag 'logo_white.svg', class:'footer__index__bottom__fma'
      .footer__index__bottom__text 
        fmarket
      .footer__index__bottom__copy 
        ©Mercari,Inc

app/views/items/_side-ber.html.haml
%main.user__mypage-main-content
  .user__mypage-left-content
    %nav{calss: "user__mypage-left-nav"}
      %ul.user__mypage-left-lists
        %li.user__mypage-left-list
          マイページ
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          お知らせ
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          やることリスト
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          いいね！一覧
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          = link_to new_item_path do
            出品する
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          出品した商品-出品中
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          出品した商品-取引中
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          出品した商品-売却済み
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          購入した商品-取引中
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          購入した商品-過去の取引
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          ニュース一覧
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          評価一覧
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          ガイド
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          お問い合わせ
          %i.fas.fa-chevron-right
      %h3.user__mypage-nav-head
        メルペイ
      %ul.user__mypage-left-lists
        %li.user__mypage-left-list
          売り上げ・振込申請
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          ポイント
          %i.fas.fa-chevron-right
      %h3.user__mypage-nav-head
        設定
      %ul.user__mypage-left-lists
        %li.user__mypage-left-list
          プロフィール
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          発送元・お届け先住所変更
          %i.fas.fa-chevron-right
        = link_to card_path(current_user) do
          %li.user__mypage-left-list
            支払い方法
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          メール/パスワード
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          本人情報
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          電話番号の確認
          %i.fas.fa-chevron-right
        %li.user__mypage-left-list
          = link_to "logout" do
            ログアウト
          %i.fas.fa-chevron-right

-# この下から書き始めてさい
          

app/views/items/edit.html.haml
.body4
  .user-single-header
    %h1
      = image_tag 'fmarket_logo_red.svg',class:"logo"
  .containar
    .item__sell-main-content
      %h2{class:"item__sell-single-head"}商品の情報を入力
      = form_for @item do |f|
        %h3.sell__upload--head
          出品画像
          %span.item__sell--uploadbox__form-require 必須
          %p 最大１０枚までアップロードできます
          .item__sell-dropbox
            .item__sell-dropbox-item
            %label{class:"image-upload-box"}
              %p ドラッグアンドドロップ
              %p またはクリックしてファイルをアップロード
              = f.label :image do
                = f.file_field :image,class:"sell-upload-drop-file"
            .item__sell-content
              %label
                商品名
              %span.item__sell--uploadbox__form-require 必須
              = f.text_field :name, placeholder: "商品名（必須 40文字まで)", class: "item__sell-content__input-default"
              .item__sell-content__form-group
                %label
                商品の説明        
                %span.item__sell--uploadbox__form-require 必須
                = f.text_area :detail, rows: "5", placeholder: "商品の説明(必須 1,000文字以内)(色、素材、重さ、定価、注意点など)例)2010年頃に1万円で購入したジャケットです。ライトグレーで傷はありません。あわせやすいのでおすすめです。", class: "item__sell--textarea-default"
              .item__sell-content__style_counter  0/1000
            .item__sell-contentsub
              .item__sell-contentsub__sub-head 商品の詳細
              .item__sell-form-box
                .item__sell-form-box__group2
                  %label
                    カテゴリー
                  %span.item__sell--uploadbox__form-require 必須
                .item__sell-select
                  %i.fas.fa-chevron-down 
                  .item__sell-select__default
                    = f.select :category_id, [["選択してください", 0],[ "レディース", 1],["メンズ", 196],["ベビー・キッズ", 341],["インテリア・住まい・小物", 477],["本・音楽・ゲーム", 618],["おもちゃ・ホビー・グッズ", 677],["コスメ・香水・美容", 790],["家電・スマホ・カメラ", 890],["スポーツ・レジャー", 975],["ハンドメイド", 1083],["チケット", 1134],["自動車・オートバイ", 1193],["その他", 1255],], {}, {class: "item__sell-select-default"}
                      
                .item__sell-form-box__group2
                  %label
                    商品の状態
                  %span.item__sell--uploadbox__form-require 必須
                .item__sell-select
                  %i.fas.fa-chevron-down
                  .item__sell-select__default
                    = f.select :state, [["選択してください","選択してください"],["新品、未使用","新品、未使用"],["未使用に近い","未使用に近い"],["目立った傷や汚れなし","目立った傷や汚れなし"],["やや傷や汚れあり","やや傷や汚れあり"],["傷や汚れあり","傷や汚れあり"],["全体的に状態が悪い","全体的に状態が悪い"]], {}, {class: "item__sell-select-default"}         
            .item__sell-content-sub2
              %p.item__sell-content-sub2__sub-head2 配送について
              %a.item__sell-content-sub2__form-question{href: "", target: "_blank"} ?
              .item__sell-form-box2
                .item__sell-content-sub2__form-group3
                  %label
                    配送料の負担
                  %span.item__sell--uploadbox__form-require 必須
                .item__sell-select
                  %i.fas.fa-chevron-down
                  .item__sell-select__default
                    = f.select :delivery_fee, [["選択してください", 0],["送料込み(出品者負担)", 1],["着払い(購入者負担)", 2]], {}, {class: "item__sell-select-default"}

                .item__sell-content-sub2__form-group4
                  %label
                    発送元の地域
                  %span.item__sell--uploadbox__form-require 必須
                  .item__sell-select
                    %i.fas.fa-chevron-down
                    .item__sell-select__default
                      = f.collection_select :prefecture_id, Prefecture.all, :id, :name , {}, {class: "item__sell-select-default"}
                .item__sell-content-sub2__form-group5
                  %label.label 発送までの日数
                  %span.item__sell--uploadbox__form-require 必須
                  .item__sell-select
                    %i.fas.fa-chevron-down
                    .item__sell-select__default
                      = f.select :delivery_date, [["選択してください", 0],["1~2日で発送", 1],["2~3日で発送", 2],["4~7日で発送", 3]], {}, {class: "item__sell-select-default"}
            .item__sell-content-low
              %p.item__sell-sub-head2 販売価格(300~9,999,999)
              %a.item__sell-content-low__form-question2{href: "", target: "_blank"} ?
              .item__sell-content-low__form-box3
                %ul.item__sell-price
                  %li.item__sell-price__form-group6
                    %label.l-left
                      価格
                      %span.item__sell--uploadbox__form-require 必須
                    .item__sell-right-group
                      %p.en ￥  
                      = f.text_field :price, placeholder: "例)300", class: "l-right-input"
                  %li.item__sell-form-group7
                    %p.l-left 販売手数料(10%)
                    .item__right-group
                      %p.l-right
                  %li.item__sell-form-group7
                    %p.l-left2 販売利益
                    .item__right-group
                      %p.l-right2
            .item__sell-content-btn-box
              .item__sell-content-btn-box__message
              %button.item__sell-content-btn-box__button{type: "submit" }
                変更する
              = link_to 'キャンセル', '#', class: "item__sell-btn-gray"

              .item__sell-overlay
    .login-footer
      .footer__nav
        %ul.footer__nav__messages
          %li.message プライバシーポリシー
          %li.message メルカリ利用規約
          %li.message 特定商取引に関する表記
      .footer__logo
        = image_tag 'logo_gray.svg',class:"flogo"
      %p.copy ©Mercari,Inc.                      

app/views/items/edit_profile.html.haml
.top-edit__profile
  = render 'items/side-ber'
  .edit-profile
    .edit-profile__title
      .edit-profile__title__content
        プロフィール
    .edit-profile__myimage
      .edit-profile__mypage__content
        .edit-profile__mypage__content__form
          %i.far.fa-user-circle{class:"user-icon2"}
          %form_with.edit-profile-form{action: '#'}
            %input.edit-profile__mypage__content__form__input{mane: "keyword", placeholder: "  例）私、売ります。", type: "search", value: ""}/
    
    .edit-profile__message
      .edit-profile__message__content
        %textarea.edit-profile-content___area{placeholder: "  例）今なら○％OFF！家計を応援しますサマーセール！家計応援価格でご提供します得しちゃおう	まとめ買いで得しちゃおう！クーポン利用で、得しちゃおう！ご奉仕価格	半期に一度のご奉仕価格！３日限りのご奉仕価格！売り尽くし	大決算売り尽くしセール！リニューアルにつき売り尽くし！夏のトレンドを納得のプライスで！毎日使うものだから納得の価格で！", value: ""}
        %button.edit-profile__message__button{type: "sabmit"}
          変更する


  .exhibit
    %form_with.exhibit__form{action: "#"}
      %button.exhibit__form__button{type: "sabmit"}
        .exhibit__form__button__logo
          出品
        = icon('fas', 'camera', class: 'exhibit__form__button__icon1')

app/views/items/identification.html.haml
.identification
  = render 'items/side-ber'
  .iden__main

    %h2.iden__title 本人情報ページ
    .iden__box
      %p.iden__text
        お客さまの本人情報をご登録ください。
        %br/
        登録されたお名前・生年月日を変更する場合、本人確認書類の提出が必要になります。
        %p.iden__text__right
          = link_to "本人確認書類のアップロード", class: "iden__text__non"
          %i.fas.fa-chevron-right-btn
          
      .iden__form-group
        %label お名前
        %p テックエキスパート 
      .iden__form-group
        %label お名前カナ
        %p テックエキスパート 
      .iden__form-group
        %label{for: "zip_code"} 郵便番号
        %span.form-arbitrary 任意
        %input.iden__input-default{name: "zip_code", placeholder: "例）1234567", type: "text", value: ""}/
      .iden__form-group
        %label{for: "prefecture"} 都道府県
        %span.form-arbitrary 任意
        %i.fas.fa-arrow-bottom
        %select.iden__input-default{name: "prefecture"}
          %option{value: ""} --
          %option{value: "1"} 北海道
          %option{value: "2"} 青森県
          %option{value: "3"} 岩手県
          %option{value: "4"} 宮城県
          %option{value: "5"} 秋田県
          %option{value: "6"} 山形県
          %option{value: "7"} 福島県
          %option{value: "8"} 茨城県
          %option{value: "9"} 栃木県
          %option{value: "10"} 群馬県
          %option{value: "11"} 埼玉県
          %option{value: "12"} 千葉県
          %option{value: "13"} 東京都
          %option{value: "14"} 神奈川県
          %option{value: "15"} 新潟県
          %option{value: "16"} 富山県
          %option{value: "17"} 石川県
          %option{value: "18"} 福井県
          %option{value: "19"} 山梨県
          %option{value: "20"} 長野県
          %option{value: "21"} 岐阜県
          %option{value: "22"} 静岡県
          %option{value: "23"} 愛知県
          %option{value: "24"} 三重県
          %option{value: "25"} 滋賀県
          %option{value: "26"} 京都府
          %option{value: "27"} 大阪府
          %option{value: "28"} 兵庫県
          %option{value: "29"} 奈良県
          %option{value: "30"} 和歌山県
          %option{value: "31"} 鳥取県
          %option{value: "32"} 島根県
          %option{value: "33"} 岡山県
          %option{value: "34"} 広島県
          %option{value: "35"} 山口県
          %option{value: "36"} 徳島県
          %option{value: "37"} 香川県
          %option{value: "38"} 愛媛県
          %option{value: "39"} 高知県
          %option{value: "40"} 福岡県
          %option{value: "41"} 佐賀県
          %option{value: "42"} 長崎県
          %option{value: "43"} 熊本県
          %option{value: "44"} 大分県
          %option{value: "45"} 宮崎県
          %option{value: "46"} 鹿児島県
          %option{value: "47"} 沖縄県
      .iden__form-group
        %label{for: "city"} 市区町村
        %span.form-arbitrary 任意
        %input.iden__input-default{name: "city", placeholder: "例）大阪市中央区", type: "text", value: ""}/
      .iden__form-group
        %label{for:    "address1_label"} 番地
        %span.form-arbitrary 任意
        %input.iden__input-default{name: "address1", placeholder: "例）難波5丁目1-60", type: "text", value: ""}/
      .iden__form-group
        %label{for: "address2_label"} 建物名
        %span.form-arbitrary 任意
        %input.iden__input-default{name: "address2", placeholder: "例）なんばスカイオ15F", type: "text", value: ""}/
        %button.btn-default{type: "submit"} 登録する
      %p.iden__text__right
        = link_to "本人確認書類のアップロード", class: "iden__text__non"
        %i.fas.fa-chevron-right-btn

app/views/items/index.html.haml
.notifications
  - flash.each do |key, value|
    = content_tag(:div, value, class: key)

.slick
  = image_tag src="nww-coffetop-thumb-720xauto-160871.jpg"

.item__area
  .category_title_area
    %p.category_title 人気のカテゴリー
    .category_items
      %p
        =link_to "レディース", { anchor: "" }, class: "items_content"
      %p
        =link_to "メンズ", { anchor: "" }, class: "items_content"
      %p
        =link_to "家電・スマホ・カメラ", { anchor: "" }, class: "items_content"
      %p
        =link_to "おもちゃ・ホビー・グッズ", { anchor: "" }, class: "items_content"

  .mainpage__items
    .mainpage__title
      %p.mainpage__title__name レディース新着アイテム
      =link_to "もっと見る＞", { anchor: "" },class: "mainpage__title__look"
    
    - @items.each do |item|
      %li.ladies__box__photo
        =link_to "items/#{item.id}" do
          = image_tag "#{item.image}", class: "ladies-photo"
          .ladies__comment-box
            .ladies__comment-box__text
              = simple_format(item.name)
          .ladies__price-box
            .ladies__price-box__price
              ¥
              = item.price
        - if item.buyer_id.present?
          .ladies__box__photo__sold

app/views/items/logout.html.haml
- breadcrumb :logout
= render "layouts/breadcrumbs"
.top-logout__page
  = render 'items/side-ber'
  .logout__page
    .logout__page__form
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: "logout__page__form__btn-red"

  .exhibit
    %form_with.exhibit__form{action: "#"}
      %button.exhibit__form__button{type: "sabmit"}
        .exhibit__form__button__logo
          出品
        = icon('fas', 'camera', class: 'exhibit__form__button__icon1')

app/views/items/mypage.html.haml
- breadcrumb :mypage
= render "layouts/breadcrumbs"
.mypage-container
  = render "items/side-ber"
  .mypage-contents
    .mypage-content
      .mypage-content__header
        .mypage-content__header__main
          .mypage-content__header__main__icon
            %i.fas.fa-user-circle
          .mypage-content__header__main__name
            = current_user.nickname
          .mypage-content__header__main__bottom
            .mypage-content__header__main__bottom__review
              評価
              .mypage-content__header__main__bottom__review__num
                10
            .mypage-content__header__main__bottom__products
              出品数
              .mypage-content__header__main__bottom__products__num
                12
      
      .mypage-content__body
        .mypage-content__body--tab
          %label.mypage-content__body--tab--notice
            お知らせ
          %label.mypage-content__body--tab--todo
            やることリスト
            
            -# ここから下をrenderで繰り返し
        .mypage-content__body--notice
          .mypage-content__body--notice__message
            .mypage-content__body--notice__message__icon
              %i.fas.fa-user-circle
            .mypage-content__body--notice__message__main
              .mypage-content__body--notice__message__main__message
                noticeかりおき〜〜〜〜〜
              .mypage-content__body--notice__message__main__time
                .mypage-content__body--notioce__message__main__time--date-icon
                  %i.far.fa-clock
                .mypage-content__body--notice__message__main__time--date
                  notice12月12日

        .mypage-content__body--list
          .mypage-content__body--list--btn
            一覧を見る
        
      .mypage-content__deal
        .mypage-content__deal--text
          購入した商品
        .mypage-content__deal--tab
          %label.mypage-content__deal--tab--now
            取引中
          %label.mypage-content__deal--tab--end
            過去の取引


        .mypage-content__deal--now
          .mypage-content__deal--now__message
            .mypage-content__deal--now__message__icon
              %i.fas.fa-user-circle
            .mypage-content__deal--now__message__main
              .mypage-content__deal--now__message__main__message
                dealかりおき〜〜〜〜〜
              .mypage-content__deal--now__message__main__time
                .mypage-content__deal--now__message__main__time--date-icon
                  %i.far.fa-clock
                .mypage-content__deal--now__message__main__time--date
                  deal 12月10日

        .mypage-content__body--list
          .mypage-content__body--list--btn
            一覧を見る