config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {
    :omniauth_callbacks => "users/omniauth_callbacks"
  }
  
  root "items#index"

  resources :items
  get 'logout', to: 'items#logout'
  get 'identification', to: 'items#identification'
  get 'edit_profile', to: 'items#edit_profile'
  get 'item_edit_delete', to: 'items#item_edit_delete'

  get 'identification', to: 'items#identification'
  get 'identification', to: 'items#identification'
  get 'mypage', to: 'items#mypage'
  

  get 'purchase/:id', to: 'purchase#index'

  resources :purchase, only: [:index,:update] do
    member do
      post 'pay'
      get 'done'
    end
  end
  
  resources :users, only: [:new, :edit, :create, :show]
  

  resources :signup, except:[:index,:show] do
    collection do
      get 'step1'
      post 'save_step1'
      post 'step2'
      post 'save_step2'
      post 'step3'
      post 'save_step3'
      get 'complete' # 登録完了後のページ
    end
  end


  get 'mypage/credit/:id', to: 'cards#credit'
  get 'registration', to: 'cards#registration'

  resources :cards, only: [:new, :create, :show, :destroy]

end

app/models/card.rb
class Card < ApplicationRecord
  belongs_to :user
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController

  require "payjp"

  def new
    @card = Card.new
  end

  def create
    Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
    customer = Payjp::Customer.create(
      description: 'test',
      card: params["payjp_token"]
    )
    @card = Card.new(user_id:current_user.id,customer_id:customer.id,card_id:customer.cards.data[0].id)

    @card.save
    redirect_to card_path(current_user)
  end

  def destroy #PayjpとCardデータベースを削除します
    card = Card.where(user_id: current_user.id).first
    if card.blank?
      redirect_to action: "new" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      customer.delete
      card.delete
      redirect_to card_path
    end
  end

  def show #Cardのデータpayjpに送り情報を取り出します
    card = Card.where(user_id:current_user.id).first
    if card.blank?
      render  "/cards/show" 
    else
      Payjp.api_key = ENV["PAYJP_PRIVATE_KEY"]
      customer = Payjp::Customer.retrieve(card.customer_id)
      @card_information = customer.cards.retrieve(card.card_id)
    end
  end
end

app/helpers/cards_helper.rb
module CardsHelper
end

app/views/cards/new.html.haml
= render 'items/header'
.wrapper
  = render "items/side-ber"
  .user-main
    .user-member-info
      %h2.user-member-info__title 支払い方法
      = form_with model: @card ,url: cards_path, name: "charge-form", id: 'charge-form' do |form|
        .user-single-content
          .user-form-group
            %p
              カード番号
              %span.required 必須
            = form.text_field :card_id, id: "card_number", placeholder: "半角数字のみ" ,class: "card-num-field", type: "text", maxlength: "16"
            %ul.user-cards
              %li.user-cards__card= image_tag 'visa.gif',class:"card-logo"
              %li.user-cards__card= image_tag 'mastercard.gif',class:"card-logo"
              %li.user-cards__card= image_tag 'saison.gif',class:"card-logo"
              %li.user-cards__card= image_tag 'amex.gif',class:"card-logo"
              %li.user-cards__card= image_tag 'diners.gif',class:"card-logo"
              %li.user-cards__card= image_tag 'discover.gif',class:"card-logo"
          .user-form-group
            %p
              有効期限
              %span.required 必須
            = form.select :exp_month, 1..12, class:"security-field", name: "exp_month"
            %p 月
            = form.select :exp_year, Time.current.year..2030, class:"security-field", name: "exp_year", type: "text"
            %p 年
          .user-form-group
            %p
              セキュリティコード
              %span.required 必須
            %p= form.text_field :cvc, placeholder:"カード背面4桁もしくは3桁の番号" ,class:"security-field", maxlength: "4", type: 'text', id: "cvc", name: "cvc"
            %p
              = link_to "" do
                カード背面の番号とは
          .user-form-group
            = form.submit "追加する", class:"submit-btn", id: 'token_submit'
= render 'items/footer'

app/views/cards/show.html.haml
= render 'items/header'
.wrapper
  = render "items/side-ber"
  .credit-container
    %h2.credit-container__title
      支払い方法
    .credit-container__body
      .credit-container__body__content
        %p.credit-container__body__content__title
          クレジットカード一覧
          - if @card_information.blank?
            %br/
            .add_card
              = link_to "" do
                %i.far.fa-credit-card 
                  = link_to "クレジットカードを追加する", new_card_path
                  
          - else
            -# 以下カード情報を表示
            = form_with model:@card ,url: card_path, method: :delete do |form|
              .card-box
                .card-box__left
                  .card-logo
                    = image_tag "visa.gif", alt:"visa"
                  = "**** **** **** " + @card_information.last4
                  %br/
                  - exp_month = @card_information.exp_month.to_s
                  - exp_year = @card_information.exp_year.to_s.slice(2,3)
                  = "有効期限" + exp_month + " / " + exp_year

                .card-box__right
                  = form.submit "削除する",class:"card-btn"

        //カード情報がある場合
        -# .credit-container__body__content__info
        -#   .credit-container__body__content__info__visa
        -#   .credit-container__body__content__info__num
        -#   .credit-container__body__content__info__deadline
          
    .credit-container__body__bottom
      = link_to "" do
        %p 支払い方法について



= render 'items/footer'